debian patch

diff --git a/debian/rivendell.init b/debian/rivendell.init
--- a/debian/rivendell.init
+++ b/debian/rivendell.init
@@ -1,83 +1,212 @@
-#!/bin/bash -e
+#! /bin/bash
+##
+##    A Rivendell init script for LSB-compliant Linux systems.
+##
+##    (C) Copyright 2002-2006 Fred Gleason <fredg@paravelsystems.com>
+##
+##      $Id: rivendell-suse.in,v 1.5 2007/02/14 21:48:41 fredg Exp $
+##
+##    This program is free software; you can redistribute it and/or modify
+##    it under the terms of version 2 of the GNU General Public License as
+##    published by the Free Software Foundation;
+##
+##    This program is distributed in the hope that it will be useful,
+##    but WITHOUT ANY WARRANTY; without even the implied warranty of
+##    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+##    GNU General Public License for more details.
+##
+##    You should have received a copy of the GNU General Public License
+##    along with this program; if not, write to the Free Software
+##    Foundation, Inc., 59 Temple Place, Suite 330, 
+##    Boston, MA  02111-1307  USA
+##
+
+### BEGIN INIT INFO
+# Provides:          rivendell
+# Required-Start:    $remote_fs mysql
+# Required-Stop:     $remote_fs
+# Default-Start:     2 3 5
+# Default-Stop:      0 1 6
+# Description:       Start the Rivendell system daemons
+### END INIT INFO
+
+
+function StartDaemons {
+  if test $GPIO_START = yes ; then
+    if test -x /etc/init.d/gpio ; then
+      /etc/init.d/gpio status > /dev/null
+      if test $? -eq 3 ; then
+        /etc/init.d/gpio start
+      fi
+    fi
+  fi
+  if test $HPI_START = yes ; then
+    if test -x /etc/init.d/asihpi ; then
+      /etc/init.d/asihpi status > /dev/null
+      if test $? -eq 3 ; then
+        /etc/init.d/asihpi start
+      fi
+    fi
+  fi
+  if test $JACK_START = yes ; then
+    $( cat /etc/jackdrc ) > /dev/null 2> /dev/null &
+    echo -n $! > /var/run/rivendell/jackd.pid
+    ipcrm -M 0x5005 2> /dev/null
+    sleep 1
+  fi
+  /usr/bin/caed 2> /dev/null
+  sleep 1
+  /usr/bin/ripcd 2> /dev/null
+  sleep 1
+  /usr/bin/rdcatchd 2> /dev/null
+}
+
+
+function StopDaemons {
+  kill `cat /var/run/rivendell/rdcatchd.pid` > /dev/null 2> /dev/null
+  kill `cat /var/run/rivendell/ripcd.pid` > /dev/null 2> /dev/null
+  kill `cat /var/run/rivendell/caed.pid` > /dev/null 2> /dev/null
+  if test $JACK_START = yes ; then
 #
-# /etc/init.d/rivendell
+# FIXME
+#  Why are three kill(1) invocations necessary to stop jackd(1)?
 #
+    killall jackd > /dev/null 2> /dev/null
+    rm -f /var/run/rivendell/jackd.pid
+  fi
+}
 
-DAEMONS="caed ripcd rdcatchd"
-PIDDIR=/var/run/rivendell
-NAME=rivendell
-LABEL="Rivendell daemons"
-
-# Defaults
-RUN_MODE="init.d"
-
-# Read config file (will override defaults above)
-[ -r /etc/default/rivendell ] && . /etc/default/rivendell
-
-if [ ! -f "/etc/rd.conf" ]; then
-    echo "No /etc/rd.conf found. See documentation and /usr/share/doc/rivendell/examples/." >&2
-    exit 0
-fi
-
-DAEMON_USER=`sed -n 's/^AudioOwner=\(.*\)$/\1/p' /etc/rd.conf`
+# Set path for script functions
+export PATH=$PATH:/usr/bin:/usr/sbin
 
 # For Ubuntu, create run directory to store pid files.
 AUDIOGROUP=`sed -n 's/^AudioGroup=\(.*\)$/\1/p' /etc/rd.conf`
 if [ ! -d /var/run/rivendell ]; then
-    install --directory --mode 02775 --owner="$DAEMON_USER" --group="$AUDIOGROUP" /var/run/rivendell
+  mkdir /var/run/rivendell
+  chmod ugo+rwx /var/run/rivendell
 fi
 
-
-# Check if Rivendell daemons are started by init scripts or pam_rd.
-if [ "$RUN_MODE" != "init.d" ]; then
-    exit 0
+#
+# If the LSB Init functions exist, use them, otherwise roll our own
+#
+if test -f /lib/lsb/init-functions ; then
+  . /lib/lsb/init-functions
+else
+  function log_success_msg() {
+    echo "$1 ... done."
+  }
+  function log_failure_msg() {
+    echo "$1 ... done."
+  }
 fi
 
-for daemon in $DAEMONS; do
-    test -x /usr/bin/$daemon || exit 0
-done
+# Default sysconfig values
+GPIO_START="no"
+HPI_START="no"
+JACK_START="no"
+RUN_MODE="init.d"
 
-function start() {
-    echo -n "Starting $LABEL:"
-    for daemon in $DAEMONS; do
-	start-stop-daemon --start --oknodo --chuid $DAEMON_USER --exec "/usr/bin/$daemon"
-	echo -n " $daemon"
-    done
-    echo "."
-}
+# Override defaults, if we have the sysconfig file
+test -f /etc/default/rivendell && . /etc/default/rivendell
 
-function stop() {
-    echo -n "Stopping $LABEL:"
-    for daemon in $DAEMONS; do
-	start-stop-daemon --stop --pidfile "$PIDDIR/$daemon.pid" --oknodo --user $DAEMON_USER  --exec "/usr/bin/$daemon"
-	echo -n " $daemon"
-    done
-    echo "."
+# Check for missing binaries
+if [ ! -x /usr/bin/caed ] ; then
+  echo "caed not installed"
+  exit 5
+fi
+if [ ! -x /usr/bin/ripcd ] ; then
+  echo "ripcd not installed"
+  exit 5
+fi
+if [ ! -x /usr/bin/rdcatchd ] ; then
+  echo "rdcatchd not installed"
+  exit 5
+fi
 
-    # caed forgets sometimes the shared memory 0x5005
-    ipcrm -M 0x5005 2> /dev/null || true
-}
+# Check for existence of needed config file and read it
+if [ ! -r /etc/rd.conf ] ; then
+  echo "Missing /etc/rd.conf"
+  exit 6
+fi
+
+# Check if Rivendell daemons are started by init scripts or pam_rd. (not for rdd)
+if [[ "$RUN_MODE" != "init.d" && $0 != "/usr/bin/rdd" ]]; then
+      exit 0
+fi
 
 case "$1" in
   start)
-    if ! /usr/bin/rdadmin --check-db; then
-	echo "No database available, check that MySQL is running" >&2;
-	exit 0;
+	$0 silent-status
+	if test $? -eq 3 ; then
+	    StartDaemons
+	fi
+	$0 silent-status
+	if test $? -eq 0 ; then
+	    log_success_msg "Starting Rivendell system daemons"
+	    exit 0
+	else
+	    log_failure_msg "Starting Rivendell system daemons"
+	    exit 0
     fi
-
-    start
     ;;
   stop)
-    stop
+	StopDaemons
+	$0 silent-status
+	if test $? -eq 0 ; then
+	    log_failure_msg "Stopping Rivendell system daemons"
+	    exit 1
+	else
+	    log_success_msg "Stopping Rivendell system daemons"
+	    exit 0
+	fi
       ;;
   restart)
-    stop
-    start
+	$0 silent-status
+	if test $? -eq 0 ; then
+	    StopDaemons
+	fi
+	$0 silent-status
+	if test $? -eq 0 ; then
+	    exit 1
+	fi
+	StartDaemons
+	$0 silent-status
+	if test $? -eq 0 ; then
+	    exit 0
+	fi
+	exit 1
+	;;
+    force-reload)
+	$0 restart
+	;;
+    status)
+	$0 silent-status
+	EXIT_CODE=$?
+	if test $EXIT_CODE -eq 0 ; then
+	    echo "Rivendell system daemons running."
+	else 
+	    echo "Rivendell system daemons stopped."
+	fi
+	exit $EXIT_CODE
+	;;
+    silent-status)
+	if test -f /var/run/rivendell/caed.pid ; then
+	    if test -d /proc/`cat /var/run/rivendell/caed.pid` ; then
+		if test -f /var/run/rivendell/ripcd.pid ; then
+		    if test -d /proc/`cat /var/run/rivendell/ripcd.pid` ; then
+			if test -f /var/run/rivendell/rdcatchd.pid ; then
+			    if test -d /proc/`cat /var/run/rivendell/rdcatchd.pid` ; then
+				exit 0
+			    fi
+			fi
+		    fi
+		fi
+	    fi
+	fi
+	exit 3
     ;;
   *)
-    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}"
+	echo "Usage: $0 {start|stop|restart|force-reload|status}"
     exit 1
     ;;
 esac
-
-exit 0
